.TH OBMIN 1
.SH NAME
Obmin \- HTTP File Server.
.SH SYNOPSIS
.B obmin-extensions
.RI [\fBEXTENSION_UUID\fR]
.SH DESCRIPTION
.B Obmin Extensions
is a GUI manager of the OBMIN Server Extensions.
.SH USAGE
.TP
* Run the obmin server extensions manager:
obmin-extensions
.TP
* Open the Slideshow extension's preferences window:
obmin-extensions 6a3c0b97ba5450736bc9ebad59eb27ff
