.TH OBMIN 1
.SH NAME
Obmin \- HTTP File Server.
.SH SYNOPSIS
.B obmin-server
.RI [\fBOPTIONS\fR]
[[\fIPARAMETERS\fR] ...]
.SH DESCRIPTION
.B Obmin
is File Sharing Solution for your network.
It is lightweight HTTP File Server for GNU/Linux systems.
.SH OPTIONS
.TP
.BR \-\-help
Show the help and exit.
.TP
.BR \-\-config\ \fIFILENAME\fR
Set the \fIFILENAME\fR to the configuration file path.
.SH USAGE
.TP
* Run obmin with the configuration from config_sample.json file:
obmin-server --config ./config_sample.json
